version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: go_project_postgres
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    networks:
      - mynetwork
  # redis:
  #   image: redis:7.2.5
  #   container_name: redis
  #   environment:
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - mynetwork
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    container_name: go_project_dragonfly
    ulimits:
      memlock: -1
    ports:
      - ${DRAGONFLY_PORT}:${DRAGONFLY_PORT}
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./dragonflydata:/data
    networks:
      - mynetwork

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080
    networks:
      - mynetwork

volumes:
  dragonflydata:
  postgresdata:

networks:
  mynetwork:
    driver: bridge
