// Code generated by ent, DO NOT EDIT.

package tennisevent

import (
	"entgo.io/ent/dialect/sql"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
)

const (
	// Label holds the string label denoting the tennisevent type in the database.
	Label = "tennis_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventTennisID holds the string denoting the event_tennis_id field in the database.
	FieldEventTennisID = "event_tennis_id"
	// FieldTeamAID holds the string denoting the team_a_id field in the database.
	FieldTeamAID = "team_a_id"
	// FieldTeamBID holds the string denoting the team_b_id field in the database.
	FieldTeamBID = "team_b_id"
	// Table holds the table name of the tennisevent in the database.
	Table = "tennis_events"
)

// Columns holds all SQL columns for tennisevent fields.
var Columns = []string{
	FieldID,
	FieldEventTennisID,
	FieldTeamAID,
	FieldTeamBID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTennisIDValidator is a validator for the "event_tennis_id" field. It is called by the builders before save.
	EventTennisIDValidator func(string) error
	// TeamAIDValidator is a validator for the "team_A_id" field. It is called by the builders before save.
	TeamAIDValidator func(string) error
	// TeamBIDValidator is a validator for the "team_B_id" field. It is called by the builders before save.
	TeamBIDValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)

// OrderOption defines the ordering options for the TennisEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventTennisID orders the results by the event_tennis_id field.
func ByEventTennisID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventTennisID, opts...).ToFunc()
}

// ByTeamAID orders the results by the team_A_id field.
func ByTeamAID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamAID, opts...).ToFunc()
}

// ByTeamBID orders the results by the team_B_id field.
func ByTeamBID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamBID, opts...).ToFunc()
}
