name: flutter_app
description: 'Frontend of SquadGo'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env

flutter_native_splash:
  color: "#231502"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png



