// Code generated by ent, DO NOT EDIT.

package runningevent

import (
	"entgo.io/ent/dialect/sql"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
)

const (
	// Label holds the string label denoting the runningevent type in the database.
	Label = "running_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventRunningID holds the string denoting the event_running_id field in the database.
	FieldEventRunningID = "event_running_id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// Table holds the table name of the runningevent in the database.
	Table = "running_events"
)

// Columns holds all SQL columns for runningevent fields.
var Columns = []string{
	FieldID,
	FieldEventRunningID,
	FieldTeamID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventRunningIDValidator is a validator for the "event_running_id" field. It is called by the builders before save.
	EventRunningIDValidator func(string) error
	// TeamIDValidator is a validator for the "team_id" field. It is called by the builders before save.
	TeamIDValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)

// OrderOption defines the ordering options for the RunningEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventRunningID orders the results by the event_running_id field.
func ByEventRunningID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventRunningID, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}
