// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/asma12a/challenge-s6/ent/basketevent"
	"github.com/asma12a/challenge-s6/ent/predicate"
)

// BasketEventDelete is the builder for deleting a BasketEvent entity.
type BasketEventDelete struct {
	config
	hooks    []Hook
	mutation *BasketEventMutation
}

// Where appends a list predicates to the BasketEventDelete builder.
func (bed *BasketEventDelete) Where(ps ...predicate.BasketEvent) *BasketEventDelete {
	bed.mutation.Where(ps...)
	return bed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bed *BasketEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bed.sqlExec, bed.mutation, bed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bed *BasketEventDelete) ExecX(ctx context.Context) int {
	n, err := bed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bed *BasketEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(basketevent.Table, sqlgraph.NewFieldSpec(basketevent.FieldID, field.TypeString))
	if ps := bed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bed.mutation.done = true
	return affected, err
}

// BasketEventDeleteOne is the builder for deleting a single BasketEvent entity.
type BasketEventDeleteOne struct {
	bed *BasketEventDelete
}

// Where appends a list predicates to the BasketEventDelete builder.
func (bedo *BasketEventDeleteOne) Where(ps ...predicate.BasketEvent) *BasketEventDeleteOne {
	bedo.bed.mutation.Where(ps...)
	return bedo
}

// Exec executes the deletion query.
func (bedo *BasketEventDeleteOne) Exec(ctx context.Context) error {
	n, err := bedo.bed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{basketevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bedo *BasketEventDeleteOne) ExecX(ctx context.Context) {
	if err := bedo.Exec(ctx); err != nil {
		panic(err)
	}
}
