// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/asma12a/challenge-s6/ent/basketevent"
	"github.com/asma12a/challenge-s6/ent/predicate"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
)

// BasketEventQuery is the builder for querying BasketEvent entities.
type BasketEventQuery struct {
	config
	ctx        *QueryContext
	order      []basketevent.OrderOption
	inters     []Interceptor
	predicates []predicate.BasketEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BasketEventQuery builder.
func (beq *BasketEventQuery) Where(ps ...predicate.BasketEvent) *BasketEventQuery {
	beq.predicates = append(beq.predicates, ps...)
	return beq
}

// Limit the number of records to be returned by this query.
func (beq *BasketEventQuery) Limit(limit int) *BasketEventQuery {
	beq.ctx.Limit = &limit
	return beq
}

// Offset to start from.
func (beq *BasketEventQuery) Offset(offset int) *BasketEventQuery {
	beq.ctx.Offset = &offset
	return beq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (beq *BasketEventQuery) Unique(unique bool) *BasketEventQuery {
	beq.ctx.Unique = &unique
	return beq
}

// Order specifies how the records should be ordered.
func (beq *BasketEventQuery) Order(o ...basketevent.OrderOption) *BasketEventQuery {
	beq.order = append(beq.order, o...)
	return beq
}

// First returns the first BasketEvent entity from the query.
// Returns a *NotFoundError when no BasketEvent was found.
func (beq *BasketEventQuery) First(ctx context.Context) (*BasketEvent, error) {
	nodes, err := beq.Limit(1).All(setContextOp(ctx, beq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{basketevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (beq *BasketEventQuery) FirstX(ctx context.Context) *BasketEvent {
	node, err := beq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BasketEvent ID from the query.
// Returns a *NotFoundError when no BasketEvent ID was found.
func (beq *BasketEventQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = beq.Limit(1).IDs(setContextOp(ctx, beq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{basketevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (beq *BasketEventQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := beq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BasketEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BasketEvent entity is found.
// Returns a *NotFoundError when no BasketEvent entities are found.
func (beq *BasketEventQuery) Only(ctx context.Context) (*BasketEvent, error) {
	nodes, err := beq.Limit(2).All(setContextOp(ctx, beq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{basketevent.Label}
	default:
		return nil, &NotSingularError{basketevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (beq *BasketEventQuery) OnlyX(ctx context.Context) *BasketEvent {
	node, err := beq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BasketEvent ID in the query.
// Returns a *NotSingularError when more than one BasketEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (beq *BasketEventQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = beq.Limit(2).IDs(setContextOp(ctx, beq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{basketevent.Label}
	default:
		err = &NotSingularError{basketevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (beq *BasketEventQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := beq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BasketEvents.
func (beq *BasketEventQuery) All(ctx context.Context) ([]*BasketEvent, error) {
	ctx = setContextOp(ctx, beq.ctx, ent.OpQueryAll)
	if err := beq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BasketEvent, *BasketEventQuery]()
	return withInterceptors[[]*BasketEvent](ctx, beq, qr, beq.inters)
}

// AllX is like All, but panics if an error occurs.
func (beq *BasketEventQuery) AllX(ctx context.Context) []*BasketEvent {
	nodes, err := beq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BasketEvent IDs.
func (beq *BasketEventQuery) IDs(ctx context.Context) (ids []ulid.ID, err error) {
	if beq.ctx.Unique == nil && beq.path != nil {
		beq.Unique(true)
	}
	ctx = setContextOp(ctx, beq.ctx, ent.OpQueryIDs)
	if err = beq.Select(basketevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (beq *BasketEventQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := beq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (beq *BasketEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, beq.ctx, ent.OpQueryCount)
	if err := beq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, beq, querierCount[*BasketEventQuery](), beq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (beq *BasketEventQuery) CountX(ctx context.Context) int {
	count, err := beq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (beq *BasketEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, beq.ctx, ent.OpQueryExist)
	switch _, err := beq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (beq *BasketEventQuery) ExistX(ctx context.Context) bool {
	exist, err := beq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BasketEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (beq *BasketEventQuery) Clone() *BasketEventQuery {
	if beq == nil {
		return nil
	}
	return &BasketEventQuery{
		config:     beq.config,
		ctx:        beq.ctx.Clone(),
		order:      append([]basketevent.OrderOption{}, beq.order...),
		inters:     append([]Interceptor{}, beq.inters...),
		predicates: append([]predicate.BasketEvent{}, beq.predicates...),
		// clone intermediate query.
		sql:  beq.sql.Clone(),
		path: beq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventBasketID string `json:"event_basket_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BasketEvent.Query().
//		GroupBy(basketevent.FieldEventBasketID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (beq *BasketEventQuery) GroupBy(field string, fields ...string) *BasketEventGroupBy {
	beq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BasketEventGroupBy{build: beq}
	grbuild.flds = &beq.ctx.Fields
	grbuild.label = basketevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventBasketID string `json:"event_basket_id,omitempty"`
//	}
//
//	client.BasketEvent.Query().
//		Select(basketevent.FieldEventBasketID).
//		Scan(ctx, &v)
func (beq *BasketEventQuery) Select(fields ...string) *BasketEventSelect {
	beq.ctx.Fields = append(beq.ctx.Fields, fields...)
	sbuild := &BasketEventSelect{BasketEventQuery: beq}
	sbuild.label = basketevent.Label
	sbuild.flds, sbuild.scan = &beq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BasketEventSelect configured with the given aggregations.
func (beq *BasketEventQuery) Aggregate(fns ...AggregateFunc) *BasketEventSelect {
	return beq.Select().Aggregate(fns...)
}

func (beq *BasketEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range beq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, beq); err != nil {
				return err
			}
		}
	}
	for _, f := range beq.ctx.Fields {
		if !basketevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if beq.path != nil {
		prev, err := beq.path(ctx)
		if err != nil {
			return err
		}
		beq.sql = prev
	}
	return nil
}

func (beq *BasketEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BasketEvent, error) {
	var (
		nodes = []*BasketEvent{}
		_spec = beq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BasketEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BasketEvent{config: beq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, beq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (beq *BasketEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := beq.querySpec()
	_spec.Node.Columns = beq.ctx.Fields
	if len(beq.ctx.Fields) > 0 {
		_spec.Unique = beq.ctx.Unique != nil && *beq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, beq.driver, _spec)
}

func (beq *BasketEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(basketevent.Table, basketevent.Columns, sqlgraph.NewFieldSpec(basketevent.FieldID, field.TypeString))
	_spec.From = beq.sql
	if unique := beq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if beq.path != nil {
		_spec.Unique = true
	}
	if fields := beq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, basketevent.FieldID)
		for i := range fields {
			if fields[i] != basketevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := beq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := beq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := beq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := beq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (beq *BasketEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(beq.driver.Dialect())
	t1 := builder.Table(basketevent.Table)
	columns := beq.ctx.Fields
	if len(columns) == 0 {
		columns = basketevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if beq.sql != nil {
		selector = beq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if beq.ctx.Unique != nil && *beq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range beq.predicates {
		p(selector)
	}
	for _, p := range beq.order {
		p(selector)
	}
	if offset := beq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := beq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BasketEventGroupBy is the group-by builder for BasketEvent entities.
type BasketEventGroupBy struct {
	selector
	build *BasketEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (begb *BasketEventGroupBy) Aggregate(fns ...AggregateFunc) *BasketEventGroupBy {
	begb.fns = append(begb.fns, fns...)
	return begb
}

// Scan applies the selector query and scans the result into the given value.
func (begb *BasketEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, begb.build.ctx, ent.OpQueryGroupBy)
	if err := begb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BasketEventQuery, *BasketEventGroupBy](ctx, begb.build, begb, begb.build.inters, v)
}

func (begb *BasketEventGroupBy) sqlScan(ctx context.Context, root *BasketEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(begb.fns))
	for _, fn := range begb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*begb.flds)+len(begb.fns))
		for _, f := range *begb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*begb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := begb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BasketEventSelect is the builder for selecting fields of BasketEvent entities.
type BasketEventSelect struct {
	*BasketEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bes *BasketEventSelect) Aggregate(fns ...AggregateFunc) *BasketEventSelect {
	bes.fns = append(bes.fns, fns...)
	return bes
}

// Scan applies the selector query and scans the result into the given value.
func (bes *BasketEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bes.ctx, ent.OpQuerySelect)
	if err := bes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BasketEventQuery, *BasketEventSelect](ctx, bes.BasketEventQuery, bes, bes.inters, v)
}

func (bes *BasketEventSelect) sqlScan(ctx context.Context, root *BasketEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bes.fns))
	for _, fn := range bes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
