// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/asma12a/challenge-s6/ent/eventtype"
	"github.com/asma12a/challenge-s6/ent/predicate"
)

// EventTypeDelete is the builder for deleting a EventType entity.
type EventTypeDelete struct {
	config
	hooks    []Hook
	mutation *EventTypeMutation
}

// Where appends a list predicates to the EventTypeDelete builder.
func (etd *EventTypeDelete) Where(ps ...predicate.EventType) *EventTypeDelete {
	etd.mutation.Where(ps...)
	return etd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (etd *EventTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, etd.sqlExec, etd.mutation, etd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (etd *EventTypeDelete) ExecX(ctx context.Context) int {
	n, err := etd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (etd *EventTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eventtype.Table, sqlgraph.NewFieldSpec(eventtype.FieldID, field.TypeString))
	if ps := etd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, etd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	etd.mutation.done = true
	return affected, err
}

// EventTypeDeleteOne is the builder for deleting a single EventType entity.
type EventTypeDeleteOne struct {
	etd *EventTypeDelete
}

// Where appends a list predicates to the EventTypeDelete builder.
func (etdo *EventTypeDeleteOne) Where(ps ...predicate.EventType) *EventTypeDeleteOne {
	etdo.etd.mutation.Where(ps...)
	return etdo
}

// Exec executes the deletion query.
func (etdo *EventTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := etdo.etd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventtype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (etdo *EventTypeDeleteOne) ExecX(ctx context.Context) {
	if err := etdo.Exec(ctx); err != nil {
		panic(err)
	}
}
