// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/asma12a/challenge-s6/ent/footevent"
	"github.com/asma12a/challenge-s6/ent/predicate"
)

// FootEventUpdate is the builder for updating FootEvent entities.
type FootEventUpdate struct {
	config
	hooks    []Hook
	mutation *FootEventMutation
}

// Where appends a list predicates to the FootEventUpdate builder.
func (feu *FootEventUpdate) Where(ps ...predicate.FootEvent) *FootEventUpdate {
	feu.mutation.Where(ps...)
	return feu
}

// SetEventFootID sets the "event_foot_id" field.
func (feu *FootEventUpdate) SetEventFootID(s string) *FootEventUpdate {
	feu.mutation.SetEventFootID(s)
	return feu
}

// SetNillableEventFootID sets the "event_foot_id" field if the given value is not nil.
func (feu *FootEventUpdate) SetNillableEventFootID(s *string) *FootEventUpdate {
	if s != nil {
		feu.SetEventFootID(*s)
	}
	return feu
}

// SetTeamAID sets the "team_A_id" field.
func (feu *FootEventUpdate) SetTeamAID(s string) *FootEventUpdate {
	feu.mutation.SetTeamAID(s)
	return feu
}

// SetNillableTeamAID sets the "team_A_id" field if the given value is not nil.
func (feu *FootEventUpdate) SetNillableTeamAID(s *string) *FootEventUpdate {
	if s != nil {
		feu.SetTeamAID(*s)
	}
	return feu
}

// SetTeamBID sets the "team_B_id" field.
func (feu *FootEventUpdate) SetTeamBID(s string) *FootEventUpdate {
	feu.mutation.SetTeamBID(s)
	return feu
}

// SetNillableTeamBID sets the "team_B_id" field if the given value is not nil.
func (feu *FootEventUpdate) SetNillableTeamBID(s *string) *FootEventUpdate {
	if s != nil {
		feu.SetTeamBID(*s)
	}
	return feu
}

// Mutation returns the FootEventMutation object of the builder.
func (feu *FootEventUpdate) Mutation() *FootEventMutation {
	return feu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (feu *FootEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, feu.sqlSave, feu.mutation, feu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (feu *FootEventUpdate) SaveX(ctx context.Context) int {
	affected, err := feu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (feu *FootEventUpdate) Exec(ctx context.Context) error {
	_, err := feu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (feu *FootEventUpdate) ExecX(ctx context.Context) {
	if err := feu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (feu *FootEventUpdate) check() error {
	if v, ok := feu.mutation.EventFootID(); ok {
		if err := footevent.EventFootIDValidator(v); err != nil {
			return &ValidationError{Name: "event_foot_id", err: fmt.Errorf(`ent: validator failed for field "FootEvent.event_foot_id": %w`, err)}
		}
	}
	if v, ok := feu.mutation.TeamAID(); ok {
		if err := footevent.TeamAIDValidator(v); err != nil {
			return &ValidationError{Name: "team_A_id", err: fmt.Errorf(`ent: validator failed for field "FootEvent.team_A_id": %w`, err)}
		}
	}
	if v, ok := feu.mutation.TeamBID(); ok {
		if err := footevent.TeamBIDValidator(v); err != nil {
			return &ValidationError{Name: "team_B_id", err: fmt.Errorf(`ent: validator failed for field "FootEvent.team_B_id": %w`, err)}
		}
	}
	return nil
}

func (feu *FootEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := feu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(footevent.Table, footevent.Columns, sqlgraph.NewFieldSpec(footevent.FieldID, field.TypeString))
	if ps := feu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := feu.mutation.EventFootID(); ok {
		_spec.SetField(footevent.FieldEventFootID, field.TypeString, value)
	}
	if value, ok := feu.mutation.TeamAID(); ok {
		_spec.SetField(footevent.FieldTeamAID, field.TypeString, value)
	}
	if value, ok := feu.mutation.TeamBID(); ok {
		_spec.SetField(footevent.FieldTeamBID, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, feu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{footevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	feu.mutation.done = true
	return n, nil
}

// FootEventUpdateOne is the builder for updating a single FootEvent entity.
type FootEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FootEventMutation
}

// SetEventFootID sets the "event_foot_id" field.
func (feuo *FootEventUpdateOne) SetEventFootID(s string) *FootEventUpdateOne {
	feuo.mutation.SetEventFootID(s)
	return feuo
}

// SetNillableEventFootID sets the "event_foot_id" field if the given value is not nil.
func (feuo *FootEventUpdateOne) SetNillableEventFootID(s *string) *FootEventUpdateOne {
	if s != nil {
		feuo.SetEventFootID(*s)
	}
	return feuo
}

// SetTeamAID sets the "team_A_id" field.
func (feuo *FootEventUpdateOne) SetTeamAID(s string) *FootEventUpdateOne {
	feuo.mutation.SetTeamAID(s)
	return feuo
}

// SetNillableTeamAID sets the "team_A_id" field if the given value is not nil.
func (feuo *FootEventUpdateOne) SetNillableTeamAID(s *string) *FootEventUpdateOne {
	if s != nil {
		feuo.SetTeamAID(*s)
	}
	return feuo
}

// SetTeamBID sets the "team_B_id" field.
func (feuo *FootEventUpdateOne) SetTeamBID(s string) *FootEventUpdateOne {
	feuo.mutation.SetTeamBID(s)
	return feuo
}

// SetNillableTeamBID sets the "team_B_id" field if the given value is not nil.
func (feuo *FootEventUpdateOne) SetNillableTeamBID(s *string) *FootEventUpdateOne {
	if s != nil {
		feuo.SetTeamBID(*s)
	}
	return feuo
}

// Mutation returns the FootEventMutation object of the builder.
func (feuo *FootEventUpdateOne) Mutation() *FootEventMutation {
	return feuo.mutation
}

// Where appends a list predicates to the FootEventUpdate builder.
func (feuo *FootEventUpdateOne) Where(ps ...predicate.FootEvent) *FootEventUpdateOne {
	feuo.mutation.Where(ps...)
	return feuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (feuo *FootEventUpdateOne) Select(field string, fields ...string) *FootEventUpdateOne {
	feuo.fields = append([]string{field}, fields...)
	return feuo
}

// Save executes the query and returns the updated FootEvent entity.
func (feuo *FootEventUpdateOne) Save(ctx context.Context) (*FootEvent, error) {
	return withHooks(ctx, feuo.sqlSave, feuo.mutation, feuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (feuo *FootEventUpdateOne) SaveX(ctx context.Context) *FootEvent {
	node, err := feuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (feuo *FootEventUpdateOne) Exec(ctx context.Context) error {
	_, err := feuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (feuo *FootEventUpdateOne) ExecX(ctx context.Context) {
	if err := feuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (feuo *FootEventUpdateOne) check() error {
	if v, ok := feuo.mutation.EventFootID(); ok {
		if err := footevent.EventFootIDValidator(v); err != nil {
			return &ValidationError{Name: "event_foot_id", err: fmt.Errorf(`ent: validator failed for field "FootEvent.event_foot_id": %w`, err)}
		}
	}
	if v, ok := feuo.mutation.TeamAID(); ok {
		if err := footevent.TeamAIDValidator(v); err != nil {
			return &ValidationError{Name: "team_A_id", err: fmt.Errorf(`ent: validator failed for field "FootEvent.team_A_id": %w`, err)}
		}
	}
	if v, ok := feuo.mutation.TeamBID(); ok {
		if err := footevent.TeamBIDValidator(v); err != nil {
			return &ValidationError{Name: "team_B_id", err: fmt.Errorf(`ent: validator failed for field "FootEvent.team_B_id": %w`, err)}
		}
	}
	return nil
}

func (feuo *FootEventUpdateOne) sqlSave(ctx context.Context) (_node *FootEvent, err error) {
	if err := feuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(footevent.Table, footevent.Columns, sqlgraph.NewFieldSpec(footevent.FieldID, field.TypeString))
	id, ok := feuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FootEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := feuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, footevent.FieldID)
		for _, f := range fields {
			if !footevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != footevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := feuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := feuo.mutation.EventFootID(); ok {
		_spec.SetField(footevent.FieldEventFootID, field.TypeString, value)
	}
	if value, ok := feuo.mutation.TeamAID(); ok {
		_spec.SetField(footevent.FieldTeamAID, field.TypeString, value)
	}
	if value, ok := feuo.mutation.TeamBID(); ok {
		_spec.SetField(footevent.FieldTeamBID, field.TypeString, value)
	}
	_node = &FootEvent{config: feuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, feuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{footevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	feuo.mutation.done = true
	return _node, nil
}
