// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/asma12a/challenge-s6/ent/footevent"
	"github.com/asma12a/challenge-s6/ent/predicate"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
)

// FootEventQuery is the builder for querying FootEvent entities.
type FootEventQuery struct {
	config
	ctx        *QueryContext
	order      []footevent.OrderOption
	inters     []Interceptor
	predicates []predicate.FootEvent
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FootEventQuery builder.
func (feq *FootEventQuery) Where(ps ...predicate.FootEvent) *FootEventQuery {
	feq.predicates = append(feq.predicates, ps...)
	return feq
}

// Limit the number of records to be returned by this query.
func (feq *FootEventQuery) Limit(limit int) *FootEventQuery {
	feq.ctx.Limit = &limit
	return feq
}

// Offset to start from.
func (feq *FootEventQuery) Offset(offset int) *FootEventQuery {
	feq.ctx.Offset = &offset
	return feq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (feq *FootEventQuery) Unique(unique bool) *FootEventQuery {
	feq.ctx.Unique = &unique
	return feq
}

// Order specifies how the records should be ordered.
func (feq *FootEventQuery) Order(o ...footevent.OrderOption) *FootEventQuery {
	feq.order = append(feq.order, o...)
	return feq
}

// First returns the first FootEvent entity from the query.
// Returns a *NotFoundError when no FootEvent was found.
func (feq *FootEventQuery) First(ctx context.Context) (*FootEvent, error) {
	nodes, err := feq.Limit(1).All(setContextOp(ctx, feq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{footevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (feq *FootEventQuery) FirstX(ctx context.Context) *FootEvent {
	node, err := feq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FootEvent ID from the query.
// Returns a *NotFoundError when no FootEvent ID was found.
func (feq *FootEventQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = feq.Limit(1).IDs(setContextOp(ctx, feq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{footevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (feq *FootEventQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := feq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FootEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FootEvent entity is found.
// Returns a *NotFoundError when no FootEvent entities are found.
func (feq *FootEventQuery) Only(ctx context.Context) (*FootEvent, error) {
	nodes, err := feq.Limit(2).All(setContextOp(ctx, feq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{footevent.Label}
	default:
		return nil, &NotSingularError{footevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (feq *FootEventQuery) OnlyX(ctx context.Context) *FootEvent {
	node, err := feq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FootEvent ID in the query.
// Returns a *NotSingularError when more than one FootEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (feq *FootEventQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = feq.Limit(2).IDs(setContextOp(ctx, feq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{footevent.Label}
	default:
		err = &NotSingularError{footevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (feq *FootEventQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := feq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FootEvents.
func (feq *FootEventQuery) All(ctx context.Context) ([]*FootEvent, error) {
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryAll)
	if err := feq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FootEvent, *FootEventQuery]()
	return withInterceptors[[]*FootEvent](ctx, feq, qr, feq.inters)
}

// AllX is like All, but panics if an error occurs.
func (feq *FootEventQuery) AllX(ctx context.Context) []*FootEvent {
	nodes, err := feq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FootEvent IDs.
func (feq *FootEventQuery) IDs(ctx context.Context) (ids []ulid.ID, err error) {
	if feq.ctx.Unique == nil && feq.path != nil {
		feq.Unique(true)
	}
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryIDs)
	if err = feq.Select(footevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (feq *FootEventQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := feq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (feq *FootEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryCount)
	if err := feq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, feq, querierCount[*FootEventQuery](), feq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (feq *FootEventQuery) CountX(ctx context.Context) int {
	count, err := feq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (feq *FootEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, feq.ctx, ent.OpQueryExist)
	switch _, err := feq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (feq *FootEventQuery) ExistX(ctx context.Context) bool {
	exist, err := feq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FootEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (feq *FootEventQuery) Clone() *FootEventQuery {
	if feq == nil {
		return nil
	}
	return &FootEventQuery{
		config:     feq.config,
		ctx:        feq.ctx.Clone(),
		order:      append([]footevent.OrderOption{}, feq.order...),
		inters:     append([]Interceptor{}, feq.inters...),
		predicates: append([]predicate.FootEvent{}, feq.predicates...),
		// clone intermediate query.
		sql:  feq.sql.Clone(),
		path: feq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventFootID string `json:"event_foot_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FootEvent.Query().
//		GroupBy(footevent.FieldEventFootID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (feq *FootEventQuery) GroupBy(field string, fields ...string) *FootEventGroupBy {
	feq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FootEventGroupBy{build: feq}
	grbuild.flds = &feq.ctx.Fields
	grbuild.label = footevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventFootID string `json:"event_foot_id,omitempty"`
//	}
//
//	client.FootEvent.Query().
//		Select(footevent.FieldEventFootID).
//		Scan(ctx, &v)
func (feq *FootEventQuery) Select(fields ...string) *FootEventSelect {
	feq.ctx.Fields = append(feq.ctx.Fields, fields...)
	sbuild := &FootEventSelect{FootEventQuery: feq}
	sbuild.label = footevent.Label
	sbuild.flds, sbuild.scan = &feq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FootEventSelect configured with the given aggregations.
func (feq *FootEventQuery) Aggregate(fns ...AggregateFunc) *FootEventSelect {
	return feq.Select().Aggregate(fns...)
}

func (feq *FootEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range feq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, feq); err != nil {
				return err
			}
		}
	}
	for _, f := range feq.ctx.Fields {
		if !footevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if feq.path != nil {
		prev, err := feq.path(ctx)
		if err != nil {
			return err
		}
		feq.sql = prev
	}
	return nil
}

func (feq *FootEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FootEvent, error) {
	var (
		nodes   = []*FootEvent{}
		withFKs = feq.withFKs
		_spec   = feq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, footevent.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FootEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FootEvent{config: feq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, feq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (feq *FootEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := feq.querySpec()
	_spec.Node.Columns = feq.ctx.Fields
	if len(feq.ctx.Fields) > 0 {
		_spec.Unique = feq.ctx.Unique != nil && *feq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, feq.driver, _spec)
}

func (feq *FootEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(footevent.Table, footevent.Columns, sqlgraph.NewFieldSpec(footevent.FieldID, field.TypeString))
	_spec.From = feq.sql
	if unique := feq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if feq.path != nil {
		_spec.Unique = true
	}
	if fields := feq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, footevent.FieldID)
		for i := range fields {
			if fields[i] != footevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := feq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := feq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := feq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := feq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (feq *FootEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(feq.driver.Dialect())
	t1 := builder.Table(footevent.Table)
	columns := feq.ctx.Fields
	if len(columns) == 0 {
		columns = footevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if feq.sql != nil {
		selector = feq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if feq.ctx.Unique != nil && *feq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range feq.predicates {
		p(selector)
	}
	for _, p := range feq.order {
		p(selector)
	}
	if offset := feq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := feq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FootEventGroupBy is the group-by builder for FootEvent entities.
type FootEventGroupBy struct {
	selector
	build *FootEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fegb *FootEventGroupBy) Aggregate(fns ...AggregateFunc) *FootEventGroupBy {
	fegb.fns = append(fegb.fns, fns...)
	return fegb
}

// Scan applies the selector query and scans the result into the given value.
func (fegb *FootEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fegb.build.ctx, ent.OpQueryGroupBy)
	if err := fegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FootEventQuery, *FootEventGroupBy](ctx, fegb.build, fegb, fegb.build.inters, v)
}

func (fegb *FootEventGroupBy) sqlScan(ctx context.Context, root *FootEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fegb.fns))
	for _, fn := range fegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fegb.flds)+len(fegb.fns))
		for _, f := range *fegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FootEventSelect is the builder for selecting fields of FootEvent entities.
type FootEventSelect struct {
	*FootEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fes *FootEventSelect) Aggregate(fns ...AggregateFunc) *FootEventSelect {
	fes.fns = append(fes.fns, fns...)
	return fes
}

// Scan applies the selector query and scans the result into the given value.
func (fes *FootEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fes.ctx, ent.OpQuerySelect)
	if err := fes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FootEventQuery, *FootEventSelect](ctx, fes.FootEventQuery, fes, fes.inters, v)
}

func (fes *FootEventSelect) sqlScan(ctx context.Context, root *FootEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fes.fns))
	for _, fn := range fes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
