// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/asma12a/challenge-s6/ent/event"
	"github.com/asma12a/challenge-s6/ent/eventtype"
	"github.com/asma12a/challenge-s6/ent/schema"
	"github.com/asma12a/challenge-s6/ent/sport"
	"github.com/asma12a/challenge-s6/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescName is the schema descriptor for name field.
	eventDescName := eventFields[1].Descriptor()
	// event.NameValidator is a validator for the "name" field. It is called by the builders before save.
	event.NameValidator = eventDescName.Validators[0].(func(string) error)
	// eventDescAddress is the schema descriptor for address field.
	eventDescAddress := eventFields[2].Descriptor()
	// event.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	event.AddressValidator = eventDescAddress.Validators[0].(func(string) error)
	// eventDescEventCode is the schema descriptor for event_code field.
	eventDescEventCode := eventFields[3].Descriptor()
	// event.EventCodeValidator is a validator for the "event_code" field. It is called by the builders before save.
	event.EventCodeValidator = eventDescEventCode.Validators[0].(func(int16) error)
	// eventDescDate is the schema descriptor for date field.
	eventDescDate := eventFields[4].Descriptor()
	// event.DateValidator is a validator for the "date" field. It is called by the builders before save.
	event.DateValidator = eventDescDate.Validators[0].(func(string) error)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[5].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	// eventDescIsPublic is the schema descriptor for is_public field.
	eventDescIsPublic := eventFields[6].Descriptor()
	// event.DefaultIsPublic holds the default value on creation for the is_public field.
	event.DefaultIsPublic = eventDescIsPublic.Default.(bool)
	// eventDescIsFinished is the schema descriptor for is_finished field.
	eventDescIsFinished := eventFields[7].Descriptor()
	// event.DefaultIsFinished holds the default value on creation for the is_finished field.
	event.DefaultIsFinished = eventDescIsFinished.Default.(bool)
	// eventDescEventTypeID is the schema descriptor for event_type_id field.
	eventDescEventTypeID := eventFields[8].Descriptor()
	// event.EventTypeIDValidator is a validator for the "event_type_id" field. It is called by the builders before save.
	event.EventTypeIDValidator = eventDescEventTypeID.Validators[0].(func(string) error)
	// eventDescSportID is the schema descriptor for sport_id field.
	eventDescSportID := eventFields[9].Descriptor()
	// event.SportIDValidator is a validator for the "sport_id" field. It is called by the builders before save.
	event.SportIDValidator = eventDescSportID.Validators[0].(func(string) error)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() string)
	// event.IDValidator is a validator for the "id" field. It is called by the builders before save.
	event.IDValidator = eventDescID.Validators[0].(func(string) error)
	eventtypeFields := schema.EventType{}.Fields()
	_ = eventtypeFields
	// eventtypeDescName is the schema descriptor for name field.
	eventtypeDescName := eventtypeFields[1].Descriptor()
	// eventtype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	eventtype.NameValidator = eventtypeDescName.Validators[0].(func(string) error)
	// eventtypeDescID is the schema descriptor for id field.
	eventtypeDescID := eventtypeFields[0].Descriptor()
	// eventtype.DefaultID holds the default value on creation for the id field.
	eventtype.DefaultID = eventtypeDescID.Default.(func() string)
	// eventtype.IDValidator is a validator for the "id" field. It is called by the builders before save.
	eventtype.IDValidator = eventtypeDescID.Validators[0].(func(string) error)
	sportFields := schema.Sport{}.Fields()
	_ = sportFields
	// sportDescName is the schema descriptor for name field.
	sportDescName := sportFields[1].Descriptor()
	// sport.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sport.NameValidator = sportDescName.Validators[0].(func(string) error)
	// sportDescID is the schema descriptor for id field.
	sportDescID := sportFields[0].Descriptor()
	// sport.DefaultID holds the default value on creation for the id field.
	sport.DefaultID = sportDescID.Default.(func() string)
	// sport.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sport.IDValidator = sportDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
