// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
	"github.com/asma12a/challenge-s6/ent/tennisevent"
)

// TennisEventCreate is the builder for creating a TennisEvent entity.
type TennisEventCreate struct {
	config
	mutation *TennisEventMutation
	hooks    []Hook
}

// SetEventTennisID sets the "event_tennis_id" field.
func (tec *TennisEventCreate) SetEventTennisID(s string) *TennisEventCreate {
	tec.mutation.SetEventTennisID(s)
	return tec
}

// SetTeamA sets the "team_A" field.
func (tec *TennisEventCreate) SetTeamA(s string) *TennisEventCreate {
	tec.mutation.SetTeamA(s)
	return tec
}

// SetTeamB sets the "team_B" field.
func (tec *TennisEventCreate) SetTeamB(s string) *TennisEventCreate {
	tec.mutation.SetTeamB(s)
	return tec
}

// SetID sets the "id" field.
func (tec *TennisEventCreate) SetID(u ulid.ID) *TennisEventCreate {
	tec.mutation.SetID(u)
	return tec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tec *TennisEventCreate) SetNillableID(u *ulid.ID) *TennisEventCreate {
	if u != nil {
		tec.SetID(*u)
	}
	return tec
}

// Mutation returns the TennisEventMutation object of the builder.
func (tec *TennisEventCreate) Mutation() *TennisEventMutation {
	return tec.mutation
}

// Save creates the TennisEvent in the database.
func (tec *TennisEventCreate) Save(ctx context.Context) (*TennisEvent, error) {
	tec.defaults()
	return withHooks(ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TennisEventCreate) SaveX(ctx context.Context) *TennisEvent {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TennisEventCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TennisEventCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tec *TennisEventCreate) defaults() {
	if _, ok := tec.mutation.ID(); !ok {
		v := tennisevent.DefaultID()
		tec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TennisEventCreate) check() error {
	if _, ok := tec.mutation.EventTennisID(); !ok {
		return &ValidationError{Name: "event_tennis_id", err: errors.New(`ent: missing required field "TennisEvent.event_tennis_id"`)}
	}
	if v, ok := tec.mutation.EventTennisID(); ok {
		if err := tennisevent.EventTennisIDValidator(v); err != nil {
			return &ValidationError{Name: "event_tennis_id", err: fmt.Errorf(`ent: validator failed for field "TennisEvent.event_tennis_id": %w`, err)}
		}
	}
	if _, ok := tec.mutation.TeamA(); !ok {
		return &ValidationError{Name: "team_A", err: errors.New(`ent: missing required field "TennisEvent.team_A"`)}
	}
	if v, ok := tec.mutation.TeamA(); ok {
		if err := tennisevent.TeamAValidator(v); err != nil {
			return &ValidationError{Name: "team_A", err: fmt.Errorf(`ent: validator failed for field "TennisEvent.team_A": %w`, err)}
		}
	}
	if _, ok := tec.mutation.TeamB(); !ok {
		return &ValidationError{Name: "team_B", err: errors.New(`ent: missing required field "TennisEvent.team_B"`)}
	}
	if v, ok := tec.mutation.TeamB(); ok {
		if err := tennisevent.TeamBValidator(v); err != nil {
			return &ValidationError{Name: "team_B", err: fmt.Errorf(`ent: validator failed for field "TennisEvent.team_B": %w`, err)}
		}
	}
	return nil
}

func (tec *TennisEventCreate) sqlSave(ctx context.Context) (*TennisEvent, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TennisEventCreate) createSpec() (*TennisEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &TennisEvent{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(tennisevent.Table, sqlgraph.NewFieldSpec(tennisevent.FieldID, field.TypeString))
	)
	if id, ok := tec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tec.mutation.EventTennisID(); ok {
		_spec.SetField(tennisevent.FieldEventTennisID, field.TypeString, value)
		_node.EventTennisID = value
	}
	if value, ok := tec.mutation.TeamA(); ok {
		_spec.SetField(tennisevent.FieldTeamA, field.TypeString, value)
		_node.TeamA = value
	}
	if value, ok := tec.mutation.TeamB(); ok {
		_spec.SetField(tennisevent.FieldTeamB, field.TypeString, value)
		_node.TeamB = value
	}
	return _node, _spec
}

// TennisEventCreateBulk is the builder for creating many TennisEvent entities in bulk.
type TennisEventCreateBulk struct {
	config
	err      error
	builders []*TennisEventCreate
}

// Save creates the TennisEvent entities in the database.
func (tecb *TennisEventCreateBulk) Save(ctx context.Context) ([]*TennisEvent, error) {
	if tecb.err != nil {
		return nil, tecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*TennisEvent, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TennisEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TennisEventCreateBulk) SaveX(ctx context.Context) []*TennisEvent {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TennisEventCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TennisEventCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
