// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/asma12a/challenge-s6/ent/predicate"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
	"github.com/asma12a/challenge-s6/ent/trainingevent"
)

// TrainingEventQuery is the builder for querying TrainingEvent entities.
type TrainingEventQuery struct {
	config
	ctx        *QueryContext
	order      []trainingevent.OrderOption
	inters     []Interceptor
	predicates []predicate.TrainingEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrainingEventQuery builder.
func (teq *TrainingEventQuery) Where(ps ...predicate.TrainingEvent) *TrainingEventQuery {
	teq.predicates = append(teq.predicates, ps...)
	return teq
}

// Limit the number of records to be returned by this query.
func (teq *TrainingEventQuery) Limit(limit int) *TrainingEventQuery {
	teq.ctx.Limit = &limit
	return teq
}

// Offset to start from.
func (teq *TrainingEventQuery) Offset(offset int) *TrainingEventQuery {
	teq.ctx.Offset = &offset
	return teq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (teq *TrainingEventQuery) Unique(unique bool) *TrainingEventQuery {
	teq.ctx.Unique = &unique
	return teq
}

// Order specifies how the records should be ordered.
func (teq *TrainingEventQuery) Order(o ...trainingevent.OrderOption) *TrainingEventQuery {
	teq.order = append(teq.order, o...)
	return teq
}

// First returns the first TrainingEvent entity from the query.
// Returns a *NotFoundError when no TrainingEvent was found.
func (teq *TrainingEventQuery) First(ctx context.Context) (*TrainingEvent, error) {
	nodes, err := teq.Limit(1).All(setContextOp(ctx, teq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trainingevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (teq *TrainingEventQuery) FirstX(ctx context.Context) *TrainingEvent {
	node, err := teq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TrainingEvent ID from the query.
// Returns a *NotFoundError when no TrainingEvent ID was found.
func (teq *TrainingEventQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = teq.Limit(1).IDs(setContextOp(ctx, teq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trainingevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (teq *TrainingEventQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := teq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TrainingEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TrainingEvent entity is found.
// Returns a *NotFoundError when no TrainingEvent entities are found.
func (teq *TrainingEventQuery) Only(ctx context.Context) (*TrainingEvent, error) {
	nodes, err := teq.Limit(2).All(setContextOp(ctx, teq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trainingevent.Label}
	default:
		return nil, &NotSingularError{trainingevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (teq *TrainingEventQuery) OnlyX(ctx context.Context) *TrainingEvent {
	node, err := teq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TrainingEvent ID in the query.
// Returns a *NotSingularError when more than one TrainingEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (teq *TrainingEventQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = teq.Limit(2).IDs(setContextOp(ctx, teq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trainingevent.Label}
	default:
		err = &NotSingularError{trainingevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (teq *TrainingEventQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := teq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TrainingEvents.
func (teq *TrainingEventQuery) All(ctx context.Context) ([]*TrainingEvent, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryAll)
	if err := teq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TrainingEvent, *TrainingEventQuery]()
	return withInterceptors[[]*TrainingEvent](ctx, teq, qr, teq.inters)
}

// AllX is like All, but panics if an error occurs.
func (teq *TrainingEventQuery) AllX(ctx context.Context) []*TrainingEvent {
	nodes, err := teq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TrainingEvent IDs.
func (teq *TrainingEventQuery) IDs(ctx context.Context) (ids []ulid.ID, err error) {
	if teq.ctx.Unique == nil && teq.path != nil {
		teq.Unique(true)
	}
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryIDs)
	if err = teq.Select(trainingevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (teq *TrainingEventQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := teq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (teq *TrainingEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryCount)
	if err := teq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, teq, querierCount[*TrainingEventQuery](), teq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (teq *TrainingEventQuery) CountX(ctx context.Context) int {
	count, err := teq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (teq *TrainingEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryExist)
	switch _, err := teq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (teq *TrainingEventQuery) ExistX(ctx context.Context) bool {
	exist, err := teq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrainingEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (teq *TrainingEventQuery) Clone() *TrainingEventQuery {
	if teq == nil {
		return nil
	}
	return &TrainingEventQuery{
		config:     teq.config,
		ctx:        teq.ctx.Clone(),
		order:      append([]trainingevent.OrderOption{}, teq.order...),
		inters:     append([]Interceptor{}, teq.inters...),
		predicates: append([]predicate.TrainingEvent{}, teq.predicates...),
		// clone intermediate query.
		sql:  teq.sql.Clone(),
		path: teq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventTrainingID string `json:"event_training_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TrainingEvent.Query().
//		GroupBy(trainingevent.FieldEventTrainingID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (teq *TrainingEventQuery) GroupBy(field string, fields ...string) *TrainingEventGroupBy {
	teq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrainingEventGroupBy{build: teq}
	grbuild.flds = &teq.ctx.Fields
	grbuild.label = trainingevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventTrainingID string `json:"event_training_id,omitempty"`
//	}
//
//	client.TrainingEvent.Query().
//		Select(trainingevent.FieldEventTrainingID).
//		Scan(ctx, &v)
func (teq *TrainingEventQuery) Select(fields ...string) *TrainingEventSelect {
	teq.ctx.Fields = append(teq.ctx.Fields, fields...)
	sbuild := &TrainingEventSelect{TrainingEventQuery: teq}
	sbuild.label = trainingevent.Label
	sbuild.flds, sbuild.scan = &teq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrainingEventSelect configured with the given aggregations.
func (teq *TrainingEventQuery) Aggregate(fns ...AggregateFunc) *TrainingEventSelect {
	return teq.Select().Aggregate(fns...)
}

func (teq *TrainingEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range teq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, teq); err != nil {
				return err
			}
		}
	}
	for _, f := range teq.ctx.Fields {
		if !trainingevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if teq.path != nil {
		prev, err := teq.path(ctx)
		if err != nil {
			return err
		}
		teq.sql = prev
	}
	return nil
}

func (teq *TrainingEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TrainingEvent, error) {
	var (
		nodes = []*TrainingEvent{}
		_spec = teq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TrainingEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TrainingEvent{config: teq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, teq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (teq *TrainingEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := teq.querySpec()
	_spec.Node.Columns = teq.ctx.Fields
	if len(teq.ctx.Fields) > 0 {
		_spec.Unique = teq.ctx.Unique != nil && *teq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, teq.driver, _spec)
}

func (teq *TrainingEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(trainingevent.Table, trainingevent.Columns, sqlgraph.NewFieldSpec(trainingevent.FieldID, field.TypeString))
	_spec.From = teq.sql
	if unique := teq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if teq.path != nil {
		_spec.Unique = true
	}
	if fields := teq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trainingevent.FieldID)
		for i := range fields {
			if fields[i] != trainingevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := teq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := teq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := teq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := teq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (teq *TrainingEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(teq.driver.Dialect())
	t1 := builder.Table(trainingevent.Table)
	columns := teq.ctx.Fields
	if len(columns) == 0 {
		columns = trainingevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if teq.sql != nil {
		selector = teq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if teq.ctx.Unique != nil && *teq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range teq.predicates {
		p(selector)
	}
	for _, p := range teq.order {
		p(selector)
	}
	if offset := teq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := teq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrainingEventGroupBy is the group-by builder for TrainingEvent entities.
type TrainingEventGroupBy struct {
	selector
	build *TrainingEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tegb *TrainingEventGroupBy) Aggregate(fns ...AggregateFunc) *TrainingEventGroupBy {
	tegb.fns = append(tegb.fns, fns...)
	return tegb
}

// Scan applies the selector query and scans the result into the given value.
func (tegb *TrainingEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tegb.build.ctx, ent.OpQueryGroupBy)
	if err := tegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrainingEventQuery, *TrainingEventGroupBy](ctx, tegb.build, tegb, tegb.build.inters, v)
}

func (tegb *TrainingEventGroupBy) sqlScan(ctx context.Context, root *TrainingEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tegb.fns))
	for _, fn := range tegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tegb.flds)+len(tegb.fns))
		for _, f := range *tegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrainingEventSelect is the builder for selecting fields of TrainingEvent entities.
type TrainingEventSelect struct {
	*TrainingEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tes *TrainingEventSelect) Aggregate(fns ...AggregateFunc) *TrainingEventSelect {
	tes.fns = append(tes.fns, fns...)
	return tes
}

// Scan applies the selector query and scans the result into the given value.
func (tes *TrainingEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tes.ctx, ent.OpQuerySelect)
	if err := tes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrainingEventQuery, *TrainingEventSelect](ctx, tes.TrainingEventQuery, tes, tes.inters, v)
}

func (tes *TrainingEventSelect) sqlScan(ctx context.Context, root *TrainingEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tes.fns))
	for _, fn := range tes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
