// Code generated by ent, DO NOT EDIT.

package trainingevent

import (
	"entgo.io/ent/dialect/sql"
	"github.com/asma12a/challenge-s6/ent/predicate"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ID) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldLTE(FieldID, id))
}

// EventTrainingID applies equality check predicate on the "event_training_id" field. It's identical to EventTrainingIDEQ.
func EventTrainingID(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEQ(FieldEventTrainingID, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEQ(FieldTeamID, v))
}

// EventTrainingIDEQ applies the EQ predicate on the "event_training_id" field.
func EventTrainingIDEQ(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEQ(FieldEventTrainingID, v))
}

// EventTrainingIDNEQ applies the NEQ predicate on the "event_training_id" field.
func EventTrainingIDNEQ(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldNEQ(FieldEventTrainingID, v))
}

// EventTrainingIDIn applies the In predicate on the "event_training_id" field.
func EventTrainingIDIn(vs ...string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldIn(FieldEventTrainingID, vs...))
}

// EventTrainingIDNotIn applies the NotIn predicate on the "event_training_id" field.
func EventTrainingIDNotIn(vs ...string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldNotIn(FieldEventTrainingID, vs...))
}

// EventTrainingIDGT applies the GT predicate on the "event_training_id" field.
func EventTrainingIDGT(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldGT(FieldEventTrainingID, v))
}

// EventTrainingIDGTE applies the GTE predicate on the "event_training_id" field.
func EventTrainingIDGTE(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldGTE(FieldEventTrainingID, v))
}

// EventTrainingIDLT applies the LT predicate on the "event_training_id" field.
func EventTrainingIDLT(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldLT(FieldEventTrainingID, v))
}

// EventTrainingIDLTE applies the LTE predicate on the "event_training_id" field.
func EventTrainingIDLTE(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldLTE(FieldEventTrainingID, v))
}

// EventTrainingIDContains applies the Contains predicate on the "event_training_id" field.
func EventTrainingIDContains(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldContains(FieldEventTrainingID, v))
}

// EventTrainingIDHasPrefix applies the HasPrefix predicate on the "event_training_id" field.
func EventTrainingIDHasPrefix(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldHasPrefix(FieldEventTrainingID, v))
}

// EventTrainingIDHasSuffix applies the HasSuffix predicate on the "event_training_id" field.
func EventTrainingIDHasSuffix(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldHasSuffix(FieldEventTrainingID, v))
}

// EventTrainingIDEqualFold applies the EqualFold predicate on the "event_training_id" field.
func EventTrainingIDEqualFold(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEqualFold(FieldEventTrainingID, v))
}

// EventTrainingIDContainsFold applies the ContainsFold predicate on the "event_training_id" field.
func EventTrainingIDContainsFold(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldContainsFold(FieldEventTrainingID, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldNotIn(FieldTeamID, vs...))
}

// TeamIDGT applies the GT predicate on the "team_id" field.
func TeamIDGT(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldGT(FieldTeamID, v))
}

// TeamIDGTE applies the GTE predicate on the "team_id" field.
func TeamIDGTE(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldGTE(FieldTeamID, v))
}

// TeamIDLT applies the LT predicate on the "team_id" field.
func TeamIDLT(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldLT(FieldTeamID, v))
}

// TeamIDLTE applies the LTE predicate on the "team_id" field.
func TeamIDLTE(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldLTE(FieldTeamID, v))
}

// TeamIDContains applies the Contains predicate on the "team_id" field.
func TeamIDContains(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldContains(FieldTeamID, v))
}

// TeamIDHasPrefix applies the HasPrefix predicate on the "team_id" field.
func TeamIDHasPrefix(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldHasPrefix(FieldTeamID, v))
}

// TeamIDHasSuffix applies the HasSuffix predicate on the "team_id" field.
func TeamIDHasSuffix(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldHasSuffix(FieldTeamID, v))
}

// TeamIDEqualFold applies the EqualFold predicate on the "team_id" field.
func TeamIDEqualFold(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldEqualFold(FieldTeamID, v))
}

// TeamIDContainsFold applies the ContainsFold predicate on the "team_id" field.
func TeamIDContainsFold(v string) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.FieldContainsFold(FieldTeamID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TrainingEvent) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TrainingEvent) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TrainingEvent) predicate.TrainingEvent {
	return predicate.TrainingEvent(sql.NotPredicates(p))
}
