// Code generated by ent, DO NOT EDIT.

package basketevent

import (
	"entgo.io/ent/dialect/sql"
	"github.com/asma12a/challenge-s6/ent/predicate"
	"github.com/asma12a/challenge-s6/ent/schema/ulid"
)

// ID filters vertices based on their ID field.
func ID(id ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ulid.ID) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLTE(FieldID, id))
}

// EventBasketID applies equality check predicate on the "event_basket_id" field. It's identical to EventBasketIDEQ.
func EventBasketID(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldEventBasketID, v))
}

// TeamAID applies equality check predicate on the "team_A_id" field. It's identical to TeamAIDEQ.
func TeamAID(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldTeamAID, v))
}

// TeamBID applies equality check predicate on the "team_B_id" field. It's identical to TeamBIDEQ.
func TeamBID(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldTeamBID, v))
}

// EventBasketIDEQ applies the EQ predicate on the "event_basket_id" field.
func EventBasketIDEQ(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldEventBasketID, v))
}

// EventBasketIDNEQ applies the NEQ predicate on the "event_basket_id" field.
func EventBasketIDNEQ(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNEQ(FieldEventBasketID, v))
}

// EventBasketIDIn applies the In predicate on the "event_basket_id" field.
func EventBasketIDIn(vs ...string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldIn(FieldEventBasketID, vs...))
}

// EventBasketIDNotIn applies the NotIn predicate on the "event_basket_id" field.
func EventBasketIDNotIn(vs ...string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNotIn(FieldEventBasketID, vs...))
}

// EventBasketIDGT applies the GT predicate on the "event_basket_id" field.
func EventBasketIDGT(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGT(FieldEventBasketID, v))
}

// EventBasketIDGTE applies the GTE predicate on the "event_basket_id" field.
func EventBasketIDGTE(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGTE(FieldEventBasketID, v))
}

// EventBasketIDLT applies the LT predicate on the "event_basket_id" field.
func EventBasketIDLT(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLT(FieldEventBasketID, v))
}

// EventBasketIDLTE applies the LTE predicate on the "event_basket_id" field.
func EventBasketIDLTE(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLTE(FieldEventBasketID, v))
}

// EventBasketIDContains applies the Contains predicate on the "event_basket_id" field.
func EventBasketIDContains(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldContains(FieldEventBasketID, v))
}

// EventBasketIDHasPrefix applies the HasPrefix predicate on the "event_basket_id" field.
func EventBasketIDHasPrefix(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldHasPrefix(FieldEventBasketID, v))
}

// EventBasketIDHasSuffix applies the HasSuffix predicate on the "event_basket_id" field.
func EventBasketIDHasSuffix(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldHasSuffix(FieldEventBasketID, v))
}

// EventBasketIDEqualFold applies the EqualFold predicate on the "event_basket_id" field.
func EventBasketIDEqualFold(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEqualFold(FieldEventBasketID, v))
}

// EventBasketIDContainsFold applies the ContainsFold predicate on the "event_basket_id" field.
func EventBasketIDContainsFold(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldContainsFold(FieldEventBasketID, v))
}

// TeamAIDEQ applies the EQ predicate on the "team_A_id" field.
func TeamAIDEQ(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldTeamAID, v))
}

// TeamAIDNEQ applies the NEQ predicate on the "team_A_id" field.
func TeamAIDNEQ(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNEQ(FieldTeamAID, v))
}

// TeamAIDIn applies the In predicate on the "team_A_id" field.
func TeamAIDIn(vs ...string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldIn(FieldTeamAID, vs...))
}

// TeamAIDNotIn applies the NotIn predicate on the "team_A_id" field.
func TeamAIDNotIn(vs ...string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNotIn(FieldTeamAID, vs...))
}

// TeamAIDGT applies the GT predicate on the "team_A_id" field.
func TeamAIDGT(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGT(FieldTeamAID, v))
}

// TeamAIDGTE applies the GTE predicate on the "team_A_id" field.
func TeamAIDGTE(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGTE(FieldTeamAID, v))
}

// TeamAIDLT applies the LT predicate on the "team_A_id" field.
func TeamAIDLT(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLT(FieldTeamAID, v))
}

// TeamAIDLTE applies the LTE predicate on the "team_A_id" field.
func TeamAIDLTE(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLTE(FieldTeamAID, v))
}

// TeamAIDContains applies the Contains predicate on the "team_A_id" field.
func TeamAIDContains(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldContains(FieldTeamAID, v))
}

// TeamAIDHasPrefix applies the HasPrefix predicate on the "team_A_id" field.
func TeamAIDHasPrefix(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldHasPrefix(FieldTeamAID, v))
}

// TeamAIDHasSuffix applies the HasSuffix predicate on the "team_A_id" field.
func TeamAIDHasSuffix(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldHasSuffix(FieldTeamAID, v))
}

// TeamAIDEqualFold applies the EqualFold predicate on the "team_A_id" field.
func TeamAIDEqualFold(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEqualFold(FieldTeamAID, v))
}

// TeamAIDContainsFold applies the ContainsFold predicate on the "team_A_id" field.
func TeamAIDContainsFold(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldContainsFold(FieldTeamAID, v))
}

// TeamBIDEQ applies the EQ predicate on the "team_B_id" field.
func TeamBIDEQ(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEQ(FieldTeamBID, v))
}

// TeamBIDNEQ applies the NEQ predicate on the "team_B_id" field.
func TeamBIDNEQ(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNEQ(FieldTeamBID, v))
}

// TeamBIDIn applies the In predicate on the "team_B_id" field.
func TeamBIDIn(vs ...string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldIn(FieldTeamBID, vs...))
}

// TeamBIDNotIn applies the NotIn predicate on the "team_B_id" field.
func TeamBIDNotIn(vs ...string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldNotIn(FieldTeamBID, vs...))
}

// TeamBIDGT applies the GT predicate on the "team_B_id" field.
func TeamBIDGT(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGT(FieldTeamBID, v))
}

// TeamBIDGTE applies the GTE predicate on the "team_B_id" field.
func TeamBIDGTE(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldGTE(FieldTeamBID, v))
}

// TeamBIDLT applies the LT predicate on the "team_B_id" field.
func TeamBIDLT(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLT(FieldTeamBID, v))
}

// TeamBIDLTE applies the LTE predicate on the "team_B_id" field.
func TeamBIDLTE(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldLTE(FieldTeamBID, v))
}

// TeamBIDContains applies the Contains predicate on the "team_B_id" field.
func TeamBIDContains(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldContains(FieldTeamBID, v))
}

// TeamBIDHasPrefix applies the HasPrefix predicate on the "team_B_id" field.
func TeamBIDHasPrefix(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldHasPrefix(FieldTeamBID, v))
}

// TeamBIDHasSuffix applies the HasSuffix predicate on the "team_B_id" field.
func TeamBIDHasSuffix(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldHasSuffix(FieldTeamBID, v))
}

// TeamBIDEqualFold applies the EqualFold predicate on the "team_B_id" field.
func TeamBIDEqualFold(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldEqualFold(FieldTeamBID, v))
}

// TeamBIDContainsFold applies the ContainsFold predicate on the "team_B_id" field.
func TeamBIDContainsFold(v string) predicate.BasketEvent {
	return predicate.BasketEvent(sql.FieldContainsFold(FieldTeamBID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BasketEvent) predicate.BasketEvent {
	return predicate.BasketEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BasketEvent) predicate.BasketEvent {
	return predicate.BasketEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BasketEvent) predicate.BasketEvent {
	return predicate.BasketEvent(sql.NotPredicates(p))
}
