// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA29XDwE4dq_U32hOJ3_fVvJp3JvC272KU',
    appId: '1:471748746827:web:ea61955ea7dfa7ab18f7ce',
    messagingSenderId: '471748746827',
    projectId: 'squadgo-64368',
    authDomain: 'squadgo-64368.firebaseapp.com',
    storageBucket: 'squadgo-64368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLbqLZ4bAI4FAPHmLTQFMlqsctXo2NRc',
    appId: '1:471748746827:android:19d1d12e763c490e18f7ce',
    messagingSenderId: '471748746827',
    projectId: 'squadgo-64368',
    storageBucket: 'squadgo-64368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1O1mfMDTi6pFQsg3N4jFbro2-IR0j77o',
    appId: '1:471748746827:ios:9723ecf17d8dd83518f7ce',
    messagingSenderId: '471748746827',
    projectId: 'squadgo-64368',
    storageBucket: 'squadgo-64368.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1O1mfMDTi6pFQsg3N4jFbro2-IR0j77o',
    appId: '1:471748746827:ios:9723ecf17d8dd83518f7ce',
    messagingSenderId: '471748746827',
    projectId: 'squadgo-64368',
    storageBucket: 'squadgo-64368.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA29XDwE4dq_U32hOJ3_fVvJp3JvC272KU',
    appId: '1:471748746827:web:94da6ab2706f620018f7ce',
    messagingSenderId: '471748746827',
    projectId: 'squadgo-64368',
    authDomain: 'squadgo-64368.firebaseapp.com',
    storageBucket: 'squadgo-64368.firebasestorage.app',
  );
}
